### ISSUE TITLE
Plugin: MAL: error: invalid_token

### ISSUE THREAD

**Issue by skyborgff** [skyborgff/KaDoKo#23]
```Loading Plugin: Animeshon
Loaded as metadata
Loading Plugin: MAL
Loaded as library
Loaded as metadata
MAL: Obtaining User list
b'{"error":"invalid_token"}'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\fabio\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\fabio\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Programing\MAL-torrent-Plex-sync\Core\Tasker\TaskManager.py", line 215, in normalloop
    self._runTasks(current_tasks, current_tasks_dict)
  File "D:\Programing\MAL-torrent-Plex-sync\Core\Tasker\TaskManager.py", line 194, in _runTasks
    self.__run(tasks[task_name][0])
  File "D:\Programing\MAL-torrent-Plex-sync\Core\Tasker\TaskManager.py", line 147, in __run
    reply = callback(*task_args)
  File "D:\Programing\MAL-torrent-Plex-sync\Core\Managers\LibraryManager.py", line 24, in UpdateLibrary
    main_list = self.mainLibrary().Lists()
  File "D:\Programing\MAL-torrent-Plex-sync\Plugins\MAL\MAL.py", line 67, in Lists
    list = self.load(url)['data']
  File "D:\Programing\MAL-torrent-Plex-sync\Plugins\MAL\MAL.py", line 60, in load
    raise RuntimeError('Failed to grab data')
RuntimeError: Failed to grab data```

**Comment by skyborgff** [comment]
Fixed in 9dcc5f2c1715b4168b638a62a5dbc33aeeb822ec
